name: project_queue

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      cache_from:
        - frontend:cache
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
