name: project_queue

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
